platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'Maraca_Example' do
  pod 'MaracaPod', :path => '../'
  
  target 'Maraca_Tests' do
    inherit! :search_paths
    
  end
  
end
